baseURL = "https://www.littlepromisepress.com/"
title = "Little Promise Press"
theme = "tella"
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = true
publishDir = "../docs"
enableRobotsTXT = true
hasCJKLanguage = false

[params]
  author = "Little Promise Press"
  description = "Editorial infantil STEM con libros de ciencia divertida para ni単as y ni単os de 6 a 10 a単os."
  images = ["/img/portada-es.png"]

[languages]

  [languages.es]
    contentDir = "content/es"
    languageName = "Espa単ol"
    weight = 1
    title = "Little Promise Press"

    [languages.es.menu]
      [[languages.es.menu.main]]
        identifier = "home"
        name = "Inicio"
        url = "/es/"
        weight = 1

      [[languages.es.menu.main]]
        identifier = "books"
        name = "Libros"
        url = "/es/libros/"
        weight = 2

      [[languages.es.menu.main]]
        identifier = "about"
        name = "Sobre la editorial"
        url = "/es/sobre/"
        weight = 3

      [[languages.es.menu.main]]
        identifier = "contact"
        name = "Contacto"
        url = "/es/contacto/"
        weight = 4


  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 2
    title = "Little Promise Press"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/en/"
        weight = 1

      [[languages.en.menu.main]]
        identifier = "books"
        name = "Books"
        url = "/en/books/"
        weight = 2

      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/en/about/"
        weight = 3

      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/en/contact/"
        weight = 4

