baseURL = "https://littlepromisepress.com/"
title = "Little Promise Press"
theme = "tella"
defaultContentLanguage = "es"
publishDir = "../docs"
enableRobotsTXT = true
hasCJKLanguage = false

[params]
  author = "Little Promise Press"
  description = "Editorial infantil STEM con libros de ciencia divertida para niñas y niños de 6 a 10 años."
  images = ["/img/portada-es.png"]

[languages]
  [languages.es]
    languageName = "Español"
    weight = 1
    description = "Editorial infantil STEM que crea libros de experimentos sencillos para aprender ciencia jugando."


    [languages.es.params]
      mainMenuTitle = "Menú"

  [languages.en]
    languageName = "English"
    description = "Children’s STEM publisher creating fun science experiment books for curious kids aged 6–10."
    weight = 2

    [languages.en.params]
      mainMenuTitle = "Menu"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Inicio"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "books"
    name = "Libros"
    url = "/libros/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "Sobre la editorial"
    url = "/sobre/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contacto"
    url = "/contacto/"
    weight = 4
